### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by Pelirrojo**
Adding a Dockerfile to run a movie without installing deps.

### CODE REVIEW

**Comment by nitram509** [comment]
Hi,

I did completely forget about this PR, sorry.
May I ask you to add some little documentation in the README as well, so people do realize, a dockerized version is available?

**Comment by Pelirrojo** [comment]
Ok, I'm going to improve the input parameters and add a new block on readme.

**Comment by Pelirrojo** [comment]
Just Ready @nitram509 
I hope the README.md changes could help.

Thanks,
Manuel

**Comment by nitram509** [comment]
Awesome, Manuel,
Thank you very much for your contribution. 👍 

Regards
Martin

**Pull request merged**
